# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/src/app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/src/app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/app/CMakeFiles /usr/src/app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named messenger

# Build rule for target.
messenger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 messenger
.PHONY : messenger

# fast build rule for target.
messenger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/build
.PHONY : messenger/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/main.cpp.s
.PHONY : main.cpp.s

src/chat.o: src/chat.cpp.o

.PHONY : src/chat.o

# target to build an object file
src/chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/chat.cpp.o
.PHONY : src/chat.cpp.o

src/chat.i: src/chat.cpp.i

.PHONY : src/chat.i

# target to preprocess a source file
src/chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/chat.cpp.i
.PHONY : src/chat.cpp.i

src/chat.s: src/chat.cpp.s

.PHONY : src/chat.s

# target to generate assembly for a file
src/chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/chat.cpp.s
.PHONY : src/chat.cpp.s

src/client.o: src/client.cpp.o

.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/client_app.o: src/client_app.cpp.o

.PHONY : src/client_app.o

# target to build an object file
src/client_app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/client_app.cpp.o
.PHONY : src/client_app.cpp.o

src/client_app.i: src/client_app.cpp.i

.PHONY : src/client_app.i

# target to preprocess a source file
src/client_app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/client_app.cpp.i
.PHONY : src/client_app.cpp.i

src/client_app.s: src/client_app.cpp.s

.PHONY : src/client_app.s

# target to generate assembly for a file
src/client_app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/client_app.cpp.s
.PHONY : src/client_app.cpp.s

src/gp_chat.o: src/gp_chat.cpp.o

.PHONY : src/gp_chat.o

# target to build an object file
src/gp_chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/gp_chat.cpp.o
.PHONY : src/gp_chat.cpp.o

src/gp_chat.i: src/gp_chat.cpp.i

.PHONY : src/gp_chat.i

# target to preprocess a source file
src/gp_chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/gp_chat.cpp.i
.PHONY : src/gp_chat.cpp.i

src/gp_chat.s: src/gp_chat.cpp.s

.PHONY : src/gp_chat.s

# target to generate assembly for a file
src/gp_chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/gp_chat.cpp.s
.PHONY : src/gp_chat.cpp.s

src/message.o: src/message.cpp.o

.PHONY : src/message.o

# target to build an object file
src/message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/message.cpp.o
.PHONY : src/message.cpp.o

src/message.i: src/message.cpp.i

.PHONY : src/message.i

# target to preprocess a source file
src/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/message.cpp.i
.PHONY : src/message.cpp.i

src/message.s: src/message.cpp.s

.PHONY : src/message.s

# target to generate assembly for a file
src/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/message.cpp.s
.PHONY : src/message.cpp.s

src/pv_chat.o: src/pv_chat.cpp.o

.PHONY : src/pv_chat.o

# target to build an object file
src/pv_chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/pv_chat.cpp.o
.PHONY : src/pv_chat.cpp.o

src/pv_chat.i: src/pv_chat.cpp.i

.PHONY : src/pv_chat.i

# target to preprocess a source file
src/pv_chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/pv_chat.cpp.i
.PHONY : src/pv_chat.cpp.i

src/pv_chat.s: src/pv_chat.cpp.s

.PHONY : src/pv_chat.s

# target to generate assembly for a file
src/pv_chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/pv_chat.cpp.s
.PHONY : src/pv_chat.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... messenger"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/chat.o"
	@echo "... src/chat.i"
	@echo "... src/chat.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/client_app.o"
	@echo "... src/client_app.i"
	@echo "... src/client_app.s"
	@echo "... src/gp_chat.o"
	@echo "... src/gp_chat.i"
	@echo "... src/gp_chat.s"
	@echo "... src/message.o"
	@echo "... src/message.i"
	@echo "... src/message.s"
	@echo "... src/pv_chat.o"
	@echo "... src/pv_chat.i"
	@echo "... src/pv_chat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

